#file: noinspection UndefinedAction,UndefinedParamsPresent
name: Build and Deploy to Azure Function App
permissions:
  contents: read

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'patronauthorizationservice'
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Update lock file
      run: poetry lock

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --without dev

    - name: Build package with Poetry
      run: |
        poetry build
        mkdir -p function-package
        # Extract the wheel to get the package contents
        poetry run pip install dist/*.whl --target function-package
        # Copy function-specific files
        cp -r function_app.py host.json requirements.txt function-package/ 2>/dev/null || true
        cp -r local.settings.json function-package/ 2>/dev/null || true

    - name: Create deployment package
      run: |
        cd function-package
        zip -r ../function-app.zip . -x "*.pyc" "__pycache__/*" "*.git*"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: function-app
        path: function-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Azure (stage)
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: function-app

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: function-app.zip
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: false
        enable-oryx-build: false
